### ISSUE TITLE
[BUG] Can't Drag Tabs.

### ISSUE THREAD

**Issue by LakesideMiners** [aminomancer/uc.css.js#101]
**Link to the file containing the bug**
Issue doesn't go away even when all scripts are off.

**Describe the bug**
Can't drag tabs

**To Reproduce**
1. Attempt to drag tabs
2. Can't drag tabs
 
**Expected behavior**
I should be able to drag tabs

**Screenshots**

![TuUwkat](https://github.com/user-attachments/assets/74db2737-9713-4a74-8756-56adddbf78c9)
this was while I had some scripts still on, but the issue is still there even after dragging tabs.

**Desktop :**
 - OS: Windows 10
 - Firefox update channel: Nightly
 - Version: [e.g. 132.0a1]
 - Build ID: 20240929094629

**Additional context**
the browser console gets spammed with
```
Uncaught TypeError: can't access property "screenX", firstTab is undefined
    _animateTabMove chrome://browser/content/tabbrowser/tabs.js:1955
    on_dragover chrome://browser/content/tabbrowser/tabs.js:717
    handleEvent chrome://browser/content/tabbrowser/tabs.js:2266
```
in the file
```tabs.js:1955:24``` 

whenever I try to drag the tabs. 

This issue does not occur in a separate profile that I made without uc.ccc.js installed.

**Comment by aminomancer** [comment]
Re-download tabMods.uc.js to fix the dragging issue. Also re-download uc-tabs.css and uc-variables.css to fix the tab inline padding. Thanks for filing.

**Comment by LakesideMiners** [comment]
Both got fixed! thank you!

**Comment by aminomancer** [comment]
No problem, I have to keep it up to date since I use it myself too hah. I just don't update firefox as often as I should since I hate reloading all my tabs. So the reports are helpful.
