### ISSUE TITLE
Werid omnibox/urlbar behavor

### ISSUE THREAD

**Issue by LakesideMiners** [aminomancer/uc.css.js#102]
There are two paths this could take. 
EIther a bug report  OR just me having turned on a thing.
I opened up firefox one day and saw this when I went to go and type into the URL bar. it took up the full width of the screen, While I can see others wanting this, as it does look pretty nice imo.
I do not want this. If this is a feature I somehow turned on by mistake. then, let me know as I don't remember turning anything on.
I am using the most recent version of the scripts.
![image](https://github.com/user-attachments/assets/e7a2f0d1-55ad-4333-8d11-be88f2edc531)
Using Nightly 133.0a1 (20241025041043) on Windows 10

**Comment by LakesideMiners** [comment]
this has been fixed after pulling the changes from 2 weeks ago.
closing

**Comment by aminomancer** [comment]
Sorry, didn't see this report.
