### ISSUE TITLE
[BUG]  Private tab script doesn't work in Firefox Nightly 135a, the button of new private tab no appear in the toolbar

### ISSUE THREAD

**Issue by kaos-55** [aminomancer/uc.css.js#105]
**Link to the file containing the bug**
https://github.com/aminomancer/uc.css.js/blob/master/JS/privateTabs.uc.js

**Describe the bug**
Again bothering you, the private tab script does not work in nightly 135.0a1, the new private tab button does not show up in the toolbar. I have checked that the autoconfig works and even tried other scripts and they work, so the problem seems to be with the script.

**To Reproduce**
1. Install latest version of fx-autoconfig
2. Install privateTabs.uc.js script
3. Restart Firefox
4. New private tab button doesn´t appear in the toolbar

**Expected behavior**
After install fx-autoconfig, install the script and restart firefox the new private tab button appears in the toolbar

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Firefox update channel: Nightly
 - Version: 135.0a1
 - Build ID: 20241208

**Additional context**
I have tried old versions of the script, but none of them work on nightly.

**Comment by kaos-55** [comment]
I will add something else, after doing several tests with older versions of fx-autoconfig and Nightly, it seems that the problem is with a change (update) they made in fx-autoconfig, since it breaks part of the functionality of the script in older versions of Nightly, since the shortcut to enable private tabs works, but the pages are still stored in the history. Testing with updated Nightly and updated fx-autoconfig, the script doesn't even work. I think the script should be "refactored" to make it work again.

**Comment by aminomancer** [comment]
Regarding the new version of fx-autoconfig, update all scripts for f69580b6941f1cd2869f1010b89ba6ea0ad9c7a3.

**Comment by aminomancer** [comment]
Sorry, you actually want fc2143ef51a01f1ad334db437cc064e59b11c426. I messed up the hotkeys but they are fixed now.
