### ISSUE TITLE
[FR] Shortcut for Back/Forward menu popup

### ISSUE THREAD

**Issue by rubaboo** [aminomancer/uc.css.js#107]
**Is your feature request related to a problem? Please describe.**
I often want to jump a few steps back in history, and there is no way to do it without using the mouse...

**Describe the solution you'd like**
I want to be able to invoke the tab history menu using Alt+Down combo.

**Describe alternatives you've considered**
This code does what I want when I paste it into Console. I don't know how to bind it to a key using a user script.
```
var btnF = document.getElementById("forward-button");
btnF.menupopup.openPopup()
```

**Comment by aminomancer** [comment]
you can do it with fx-autoconfig's [hotkeys API](https://github.com/MrOtherGuy/fx-autoconfig?tab=readme-ov-file#hotkeys).

```js
let details = {
  id: "myHotkey",
  modifiers: "alt",
  key: "ArrowDown",
  command: win => {
    let button = document.getElementById("back-button");
    if (button.disabled) {
      let fwdButton = document.getElementById("forward-button");
      if (!fwdButton.disabled) button = fwdButton;
    }
    win.gClickAndHoldListenersOnElement._openMenu(button);
  },
};

UC_API.Hotkeys.define(details).autoAttach({ suppressOriginalKey: true });
```

**Comment by rubaboo** [comment]
Thank you for pointing me in the right direction. FYI the Hotkeys API [was revised](https://github.com/MrOtherGuy/fx-autoconfig/issues/59#issuecomment-2564060638) as a result of my further inquiry with the author.

**Comment by aminomancer** [comment]
Thanks for the heads up.
