### ISSUE TITLE
debugExtensionInToolbarContextMenu.uc.js

### ISSUE THREAD

**Issue by bege10** [aminomancer/uc.css.js#13]
Hello,
I use some of your helpful scripts, thank you.
Is it possible to add the menu of debugExtensionInToolbarContextMenu.uc.js also to the context menu of the addons in about:addons?

**Comment by aminomancer** [comment]
Not feasible, sorry. about:addons is a content page. It doesn't have its own context menu. All content pages use one context menu. The menuitems just get hidden/shown depending on what was clicked. It's very different from the toolbar context menu that opens when you right click an addon's toolbar button.

**Comment by bege10** [comment]
Thanks for your answer.
