### ISSUE TITLE
Window Drag Hotkey bug

### ISSUE THREAD

**Issue by henryxrl** [aminomancer/uc.css.js#19]
To reproduce the buggy behavior:
1. Hold down alt+shift and click the mouse button to drag as usual
2. Still holding the mouse button, but release the alt+shift. You can still drag around the window as expected.
3. Release the mouse button. At this point, since no alt+shift button is pressed, the mouse shouldn't be able to drag the window. But it still can do so. This makes it impossible to normally interact with the UI, like click on the urlbar to enter a new url.

**Comment by aminomancer** [comment]
Thanks, try version 1.1

**Comment by henryxrl** [comment]
Fixed. All good now! Thanks for the great work!
