### ISSUE TITLE
[BUG] openLinkInUnloadedTab.uc.js can't open links in folders

### ISSUE THREAD

**Issue by Sneakpeakcss** [aminomancer/uc.css.js#37]
**Describe the bug**
[openLinkInUnloadedTab.uc.js](https://github.com/aminomancer/uc.css.js/blob/master/JS/openLinkInUnloadedTab.uc.js) can't open links from a folder unless the folder was previously opened.

**To Reproduce**
1. Launch Firefox and hit "Open All in Unloaded Tabs" on any bookmarked folder, result: as on screenshot.
2. Launch Firefox open the folder first and then hit "Open All in Unloaded Tabs on any bookmarked folder, result: links are opened properly.

**Expected behavior**
Every link inside the folder should be opened without "previewing" the folder first.

**Screenshots**

![errorFF](https://user-images.githubusercontent.com/77424331/163077264-d72823dc-ced9-431e-80c9-e56bfe3f36e9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Firefox update channel: [ESR Portable](https://portableapps.com/apps/internet/firefox-portable-esr)
 - Version: 91.8.0esr (64-bit)
 - Build ID: 20220330151638

**Additional context**

Every time i try to load any folder that wasn't previously "previewed" it just throws the same error as on the screenshot. Opening single bookmarked links works without a problem.

**Comment by aminomancer** [comment]
Thanks, nice catch. Try version 1.5.1

**Comment by Sneakpeakcss** [comment]
Works great now, thanks for the quick update.

_Also btw… It looks like something ate the end of @description in the last update [openBookmarkInContainerTab.uc.js](https://github.com/aminomancer/uc.css.js/blob/master/JS/openBookmarkInContainerTab.uc.js#L6=)_

**Comment by aminomancer** [comment]
Whoops, thanks for pointing that out.
