### ISSUE TITLE
Potential bug with verticalTabsPanel not loading without newtab button.

### ISSUE THREAD

**Issue by Sneakpeakcss** [aminomancer/uc.css.js#43]
**Describe the bug**
I'm not sure if we can consider this as a bug or more of a "intended behavior", but it looks like [verticalTabsPane.uc.js](https://github.com/aminomancer/uc.css.js/blob/master/JS/verticalTabsPane.uc.js) really doesn't like when you remove the newTab button and simply doesn't load when it's not placed somewhere.

**To Reproduce**
1. Place the newtab button back in "customize toolbar"
2. Restart firefox

**Expected behavior**
VerticalTabsPane should load even without the newtab button being placed in the UI(?)

**Screenshots**
![bugbug](https://user-images.githubusercontent.com/77424331/168563147-e9e64abf-6f97-4577-9eeb-bf8afb22e231.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox update channel: ESR91/DEV100/Nightly102.0a1

**Comment by aminomancer** [comment]
Thanks. Not intentional, just an oversight. Try [version 1.6.1](https://github.com/aminomancer/uc.css.js/blob/master/JS/verticalTabsPane.uc.js).

**Comment by Sneakpeakcss** [comment]
Works like a charm… Thanks for a _really quick_ update.

**Comment by aminomancer** [comment]
Sure, you caught me at a good time haha.
