### ISSUE TITLE
[BUG] privateTabs Script breaking Duskfox

### ISSUE THREAD

**Issue by AlbusPercivalDumbledore** [aminomancer/uc.css.js#50]
Hey, MS. privateTabs Script is causing Tabs to behave abruptly. Its been broken since Firefox v102. 

Someone who uses your stylesheet and recently updated to v102 mentioned it to me. Reporting here, since you had mentioned you don't use that script yourself.

Tested on: Linux/Windows, Firefox versions >102

**Comment by aminomancer** [comment]
Thanks for the report, I uploaded a new version
