### ISSUE TITLE
[BUG] tabTooltipNavButtons.uc.js: Tabs history not appearing

### ISSUE THREAD

**Issue by EstherMoellman** [aminomancer/uc.css.js#52]
Hi @aminomancer ,

Firstly, your tabTooltipNavButtons.uc.js is amazing. Thank you!

I believe I may have found a bug.
Unfortunately, when I right click the back or forward button, I can't see tabs history.
This bug appeared to me few days ago.
Just in case, I tried tabTooltipNavButtons.uc.js in a Nightly clean install, no CSS mods, no add-ons, untouched. And the tabTooltipNavButtons.uc.js bug is there... on right-mouse-click over back or forward, tabs history is not shown anymore.

Just to be clear I'm talking about line 49:

    // When you right click one of the back or forward buttons, it opens a
    // little context menu that shows up to 15 items in that tab's history.

Hope you can fix it.

Thank you in advance!

**Comment by aminomancer** [comment]
Haha funny, I broke my own script with a [patch](https://hg.mozilla.org/mozilla-central/rev/34e61e1476efb312c8825278cbdd768973574f87). Try version 1.2.3, should be fixed now. Thanks for the report.

**Comment by EstherMoellman** [comment]
Beautiful! Thank you.
