### ISSUE TITLE
[BUG] Right clicking the toolbox button no longer opens the browser toolbox

### ISSUE THREAD

**Issue by watatomo** [aminomancer/uc.css.js#54]
**Describe the bug**
Right clicking the toolbox button doesn't open the browser toolbox. Instead, it shows a context menu.

**To Reproduce**
1. Go to the toolbar
2. Right click on browser toolbox

**Expected behavior**
The browser toolbox should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/23179278/190301139-9c996cb7-abf9-4bd5-8378-80198b9b21cd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Firefox update channel: Developer (Hopefully there isn't much difference with Nightly)
 - Version: 105.0b9
 - Build ID: 20220908185813

**Additional context**
My setup is published [here](https://github.com/watatomo/firefox-css).

**Comment by aminomancer** [comment]
Like the readme says, these scripts are only designed to work with Nightly. It's not possible to support every release channel. You can switch to Nightly or go back to a previous version of the script

**Comment by aminomancer** [comment]
Also you can probably make the existing version work by changing [these lines](https://github.com/aminomancer/uc.css.js/blob/87954d656021716fcd1f7b933b2948abe5a2402a/JS/atoolboxButton.uc.js#L93-L96) to this:
```
    XPCOMUtils.defineLazyModuleGetters(lazy, {
      BrowserToolboxLauncher:
        "resource://devtools/client/framework/browser-toolbox/Launcher.jsm",
    });
```

**Comment by watatomo** [comment]
Yeah, that did the trick. Apologizes.
