### ISSUE TITLE
[BUG] VerticalTabsPane Script broken on v107.0a1

### ISSUE THREAD

**Issue by AlbusPercivalDumbledore** [aminomancer/uc.css.js#58]
Hey, MS!

VerticalTabsPane Script isn't working on v107.0a1
 - OS: Linux (Mint 20.3)

Tabs are visible only when the Pane is Pinned
![1](https://user-images.githubusercontent.com/82368617/193362999-a20a99b9-2090-412c-8a0d-063d3f2a049f.png)

Once Pane is unpinned, Tabs disappear, though the Pane keeps its place.

![2](https://user-images.githubusercontent.com/82368617/193363015-b5dbbe9a-ec78-4715-852d-17c02a53b760.png)

Also, scrolling doesn't work.

Could you please make it work again?

**Comment by aminomancer** [comment]
The layout folks are still working on the modern flexbox emulation changes, so I probably won't revisit this until they're done.

In the meantime, you can add this to userChrome.css
```
#browser {
  -moz-box-layout: revert !important;
}
```

**Comment by AlbusPercivalDumbledore** [comment]
> The layout folks are still working on the modern flexbox emulation changes, so I probably won't revisit this until they're done.
> 
> In the meantime, you can add this to userChrome.css
> 
> ```
> #browser {
>   -moz-box-layout: revert !important;
> }
> ```

Ah, okay. Thanks!

**Comment by AlbusPercivalDumbledore** [comment]
I've been having another issue for quite sometime. I have over 600 Tabs open at present, and VerticalTabsPane lags considerably when showing (on hover) and hiding. 

In contrast, I installed 'Tab Center Reborn' Extension a few days back, and its been noticeably faster.

Attaching a GIF showing the same. Could you please look into this too?

![1](https://user-images.githubusercontent.com/82368617/193473391-c23bbfeb-4bac-49da-b3fe-da84f74c7824.gif)

**Comment by aminomancer** [comment]
Have you changed the hover and hover out delays? There should be an option in the context menu if you right click the pin or toggle button.

Otherwise, performance isn't really my area of expertise. I'm working on a patch to add vertical tabs to Firefox so when that moves forward I'm sure there will be some optimizations. But at a glance, the one on the left is displayed in its own extension browser. Whereas mine is running in the main thread. So maybe that has something to do with it.

**Comment by AlbusPercivalDumbledore** [comment]
I hadn't; they were both set to 100. Though, now that I have set them both to 1, it feels slightly more responsive. I don't know, could be placebo effect :D

> I'm working on a patch to add vertical tabs to Firefox so when that moves forward I'm sure there will be some optimizations.

Now, THAT'S AWESOME!

**Comment by aminomancer** [comment]
How is it working for you now?

**Comment by AlbusPercivalDumbledore** [comment]
> How is it working for you now?

Hey, sorry saw this just now. I've been using [v1.7.5](https://github.com/aminomancer/uc.css.js/blob/5426c3d07fbd8ed43148c0b4ee2c744c8fd667fd/JS/verticalTabsPane.uc.js), and its working wonderfully well :)
