### ISSUE TITLE
Adress Bar missing

### ISSUE THREAD

**Issue by Zelmanyr** [aminomancer/uc.css.js#6]
Hi, the adress bar is missing when I apply your theme.

Here : https://i.imgur.com/EtBmevQ.png

When I click the current tab I get to the adress bar : https://i.imgur.com/QnoptKU.png

Can I get the adress bar to be always on ?

Thank you for your work.

**Comment by aminomancer** [comment]
did you install the min browser script? I don't suggest you install all the scripts at once, read each one's description before deciding which to use.
