### ISSUE TITLE
[BUG] aboutCfg.uc.js is not working on Firefox r106.0.5

### ISSUE THREAD

**Issue by BliemHax** [aminomancer/uc.css.js#61]
**Describe the bug**
Very strange, I use this script with earthlng's aboutconfig module and when I try to go to "about:cfg", Firefox does not respond to anything and there is no error message from console in the browser toolbox.

**Desktop (please complete the following information):**
 - OS: Windows10 Chinese
 - Firefox update channel: Release
 - Version: 106.0.5 Chinese Version
 - Build ID:  20221104133228

**Comment by aminomancer** [comment]
See [earthlng/aboutconfig/issues/7](https://github.com/earthlng/aboutconfig/issues/7).
