### ISSUE TITLE
How to install aboutuserchrome script?

### ISSUE THREAD

**Issue by bege10** [aminomancer/uc.css.js#65]
Hello,
I use some of your helpful scripts and would like to use the new update functionality. But I don't understand how to install it.

**Comment by aminomancer** [comment]
Get [this folder](https://github.com/aminomancer/uc.css.js/tree/master/resources/aboutuserchrome) resources/aboutuserchrome and put it in your chrome/resources folder. Then get [this file](https://github.com/aminomancer/uc.css.js/blob/master/JS/aboutUserChrome.sys.mjs) and put it in your chrome/JS folder. Then restart and enter about:userchrome in the urlbar. Does that not work?

**Comment by bege10** [comment]
I eventually managed to at least not get an error when entering about:userchrome. But it showed a blank page and one of my other favorite scripts did not work any more with fx-autoconfig. I used them with this script loader:
https://github.com/Endor8/userChrome.js#userchrome-scripte----verwendung-in-firefox
Because I don't want to miss this script and perhaps some of the others are not compatible with about:userchrome I decided to waive the automatic script update. Thanks anyway.

**Comment by aminomancer** [comment]
The script manager relies on many of the features provided by fx-autoconfig. It should show an error message that fx-autoconfig is required and offer a download link. If your scripts aren't compatible with fx-autoconfig, you could ask their author(s) to make their scripts compatible. Should be pretty easy
