### ISSUE TITLE
[BUG] urlbarTabUrlIndicator.uc.js stoped to work

### ISSUE THREAD

**Issue by EstherMoellman** [aminomancer/uc.css.js#67]
Hi @aminomancer 

Your magnificent **urlbarTabUrlIndicator.uc.js** isn't working for me anymore. I tested it in other devices, doing a Firefox clean installation, using new profiles etc, and couldn't make it work.

The normal behavior you know better than me (quoting): "Upon hovering a tab, replace the urlbar's text (at least, appear to do so) with the hovered tab's URL instead of showing a normal tab tooltip". However, when I hover a tab, only two (kind of) short vertical lines appear at the urlbar. So, if you hover a tab, indeed something appears, but it is not the URL, I dare to say that is the URL totally compacted, and it seems to appear like two short vertical lines.

I'm using latest Win11 fully updated, latest Nightly fully updated (clean install, clean profile, untouched, only using your **urlbarTabUrlIndicator.uc.js**.

Your **urlbarTabUrlIndicator.uc.js** is an amazing JS script, hope you can fix it (if it has a bug).

Bunch of thanks in advance

**Comment by aminomancer** [comment]
any idea where that script is? I don't have it on the repo

**Comment by EstherMoellman** [comment]
> any idea where that script is? I don't have it on the repo

100% made by @aminomancer : )

https://github.com/aminomancer/uc.css.js/blob/master/experimental/urlbarTabUrlIndicator.uc.js

**Comment by aminomancer** [comment]
are you using any other scripts in addition to this one?

**Comment by EstherMoellman** [comment]
> are you using any other scripts in addition to this one?

Yes, I do.
But when something is not working for me, the first thing I do is to make a clean test (fresh latest FF Nightly install, new profile, no add-ons, no CSS, no JS scripts, no about:config changes, no default setting changes, untouched). And only then I install and test the buggy script.

For a long time, your magnificent **urlbarTabUrlIndicator.uc.js** always worked perfectly for me, even with my other CSS mods, JS scripts etc. Never a problem! Never a conflict. However, recently it's not working anymore. As I explained, I can see **urlbarTabUrlIndicator.uc.js** trying to work. Unfortunately it is only showing the two small vertical lines at the urlbar.

And exactly the same is happening in my clean test.

Hope you can fix it, because your **urlbarTabUrlIndicator.uc.js** was already part of my daily browsing. I really miss it a lot.

Thanks! : )

**Comment by aminomancer** [comment]
I was just checking. Any changes I make could be incompatible with some other scripts. Try the latest version now

**Comment by EstherMoellman** [comment]
> I was just checking. Any changes I make could be incompatible with some other scripts. Try the latest version now

I did a very quick test in a clean vanilla Nightly untouched fresh install, and unfortunately the new **urlbarTabUrlIndicator.uc.js** isn't working (when a tab is hovered, the urlbar is empty, clearly the script is acting on the urlbar, but instead showing the hovered tab url, the urlbar becomes empty).

I don't have time now, but I promise you, tomorrow I'm going to do lot and lot of new tests with your new version.
And then, I'll give you my real feedback.

Thank you a lot for your fast response, your time and your effort! : )

**Comment by aminomancer** [comment]
Odd, it's working for me.

**Comment by EstherMoellman** [comment]
> Odd, it's working for me.

After hours testing tons of different alternatives, unfortunately I couldn't make it work.

Once again I took latest Nightly.
All my tests were based only on fresh latest Nightly install, untouched, no add-ons, no about:config or settings changes, 100% default, new profile etc.

I also took latest https://github.com/MrOtherGuy/fx-autoconfig
Reinstalled from the scratch, just in case I tested it, and it's 100% working. I'm addicted to your JS repo, I use lot of your JS scripts, and all of them are working perfectly fine with the latest fx-autoconfig.

But, in order to avoid possible conflicts, I removed all your JS scripts, always flushed startupCache folder, and tested your newest **urlbarTabUrlIndicator.uc.js 2.2**. Sadly, the behavior always is the same: Your JS script is active and working, it does something in the urlbar, but the hovered tab URL is not appearing, when any tab is hovered the urlbar becomes blank.

I though perhaps it could be a CSS position issue. So, I did lot and lot of changes inside your script, trying to change the CSS. However, nothing worked.

But it's working for you! Therefore, I'm the problem!
I just don't know what I'm doing wrong.

So please, be patient with me, and let me ask you:

1) Are you testing your JS script in a 100% untouched fresh Nightly install?

2) Or are you testing with a modified profile folder from your own, or with another JS scripts from your own etc? Are you using "something" else, any other modification inside Nightly, any other file, folder, script etc? I'm just trying to figure out if you might be using something that I'm not using.

As I said, in my tests I can see your **urlbarTabUrlIndicator.uc.js 2.2** trying to work. Even if the urlbar is blank when a tab is hovered, that's a signal that your script is working. It just seems to me that I'm missing something little, a small detail. Again, it's seems to me that it's a CSS position issue, or something in your profile folder that I don't have etc. But I don't really know, perhaps is something more than that. It's very frustrating for me, after so many tests.

Please, do have any clue what else can I do?

Thank you for your patience.

**Comment by aminomancer** [comment]
Did you mean 2.2? Don't think I've ever submitted a 2.2. It should say 2.0

**Comment by EstherMoellman** [comment]
> Did you mean 2.2? Don't think I've ever submitted a 2.2. It should say 2.0

You're totally right. My apologies, it's 2.0.

**Comment by aminomancer** [comment]
Alright cool, please try 2.1. Thanks for reporting

**Comment by EstherMoellman** [comment]
> Alright cool, please try 2.1. Thanks for reporting

Perfect!
Wonderful!
Amazing!
Sublime!

Great job! Kudos!

I just customized a bit the line 14 (margin: 0.5px 0 0 0;), because I was experiencing a small jump inside the urlbar.

Thank you for everything, especially for your quick replay and great fix!

PS: I use several of your JS, they are so useful to me! Thank you for your amazing work.

**Comment by aminomancer** [comment]
No problem, thanks. The text is in a tooltip, not in the urlbar, so it's not part of the urlbar layout. So subpixel rounding depends on the user's display scaling factor. You can just tweak it in userChrome.css
