### ISSUE TITLE
"One-click One-off Search Buttons" possible bug?

### ISSUE THREAD

**Issue by ericpa06** [aminomancer/uc.css.js#70]
Hi. I believe the **"userChrome.urlbar.oneOffs.skipOneOffsOnArrowKey"** setting stop working on Firefox Developer 114.0b3 onwards.  At least it didn't work on my setup. It might be worth a checking. Thank you very much.

**Comment by aminomancer** [comment]
Thanks for reporting, try version 1.8.5 and lmk if that works for you.

**Comment by ericpa06** [comment]
Thanks, it worked flawlessly! :)
