### ISSUE TITLE
[BUG] The VerticalTabsPane script cannot move  to the right in versions above 113

### ISSUE THREAD

**Issue by onepiecebdy** [aminomancer/uc.css.js#73]
The VerticalTabsPane script cannot move  to the right in versions above 113,If you can, I hope you can solve this problem, thank you very much!

**Comment by benzBrake** [comment]
you can replace `MozBoxOrdinalGroup` to `order` manually

**Comment by aminomancer** [comment]
Fixed by 689118c8a334cf8fc65df01a8f70d610f8296bdd
