### ISSUE TITLE
debugExtensionInToolbarContextMenu.uc.js v1.5.0 not working

### ISSUE THREAD

**Issue by siffegh** [aminomancer/uc.css.js#76]
**Describe the bug**
debugExtensionInToolbarContextMenu.uc.js v1.5.0 isn't working

**To Reproduce**
1. install v1.5.0
2. clear startup cache

**Expected behavior**
R. click on extension icon should produce the debug option

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win7
 - Firefox update channel: release
 - Version:115.02
 - Build ID: 20230710165010

**Additional context**
It was working with 1.45.

**Comment by aminomancer** [comment]
Like the readme says, everything on this repo is designed for use with the [Nightly release channel](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly). I can't guarantee anything will work in other release channels, since that would require not updating things to work in Nightly.

**Comment by aminomancer** [comment]
By the way, you actually shouldn't be on Release channel anymore. Support for Windows 7 and 8 was removed in 115. Release users on those platforms were automatically moved to the ESR channel when updating from 114 to 115. So unless there's some bug, you're already on ESR. And unfortunately I'll never be able to provide ongoing support for ESR, as it will just grow further and further apart from Nightly.

If using the scripts on this repo is important for your workflow, I would advise switching to Windows 10 or 11 so you can install Nightly.

If staying on Windows 7 is more important, then you should grab the old versions of the scripts on here. [Here is a link to the full repo content from May 26](https://github.com/aminomancer/uc.css.js/archive/43b13c339d23c83f903d9a1eec563fade1ea197f.zip).

**Comment by siffegh** [comment]
OK, thanks. I don't know why I didn't get switched to ESR, but I'm upgrading to Win11 within the next month anyway.
