### ISSUE TITLE
[BUG] Private tab button does not get created

### ISSUE THREAD

**Issue by 2641a40fd44383320adde4b027a1d0b03bd550** [aminomancer/uc.css.js#83]
**Describe the bug**
does not create the button, yells at [this line](https://github.com/aminomancer/uc.css.js/blob/master/JS/privateTabs.uc.js#L226)

**To Reproduce**
1. Install private tabs script
2. Open Firefox
3. Open browser toolbox

**Expected behavior**
it should appear

**Desktop (please complete the following information):**
 - OS: Linux
 - Firefox update channel: Nightly
 - Version: 119.0a1
 - Build ID: 20230905215534

**Comment by aminomancer** [comment]
Feel free to reopen if the latest update doesn't fix your issue

**Comment by 2641a40fd44383320adde4b027a1d0b03bd550** [comment]
it did not, but I replaced the variable with this and it worked:
```
let privateMask = document.getElementById(
  "private-browsing-indicator-with-label"
);
```

**Comment by aminomancer** [comment]
Sorry lol, my mistake.
