### ISSUE TITLE
[BUG] A small bug in private tabs script

### ISSUE THREAD

**Issue by kaos-55** [aminomancer/uc.css.js#85]
**Describe the bug**
When using the private tab script the private browsing icon appears in the upper right corner of the tab bar even if you are not using a private tab.

**To Reproduce**
1. Install private tabs script
2. The private browsing icon appears even though you are not in a private tab.

**Expected behavior**
When installing the private tab script there should be no private browsing icon in the normal tabs.

**Screenshots**
![private-browsing](https://github.com/aminomancer/uc.css.js/assets/86812371/c6a9f5c7-a631-4d03-b97a-59b99fbaabcf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox update channel: Nightly
 - Version: 121.0a1
 - Build ID: 20231107

**Additional context**
It is worth mentioning that when the script is deactivated this icon disappears. The functionality of the script is intact except for that one annoying detail

**Comment by aminomancer** [comment]
Thanks for filing, should be fixed in v1.2.7
