### ISSUE TITLE
Private Window Homepage broken?

### ISSUE THREAD

**Issue by siffegh** [aminomancer/uc.css.js#88]
**Describe the bug**

A Private window is not displaying my home page.

**To Reproduce**

1. Open a private window.

**Expected behavior**

My home page is not displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11 Pro 23H2 Build 22631.2861
 - Firefox update channel: Nightly
 - Version: 122.0.a1
 - Build ID: 20231216213305

**Additional context**

I have no idea when this started not to work, as I don't use Private Browsing regularly.

**Comment by aminomancer** [comment]
Private windows have never shown home pages, at least not since I've been using Firefox. The home page in a private window is always about:privatebrowsing. What's this have to do with my repo anyway? If you think the behavior should be different, you should file a bug on https://bugzilla.mozilla.org/.

**Comment by siffegh** [comment]
https://github.com/aminomancer/uc.css.js/blob/master/JS/privateWindowHomepage.uc.js??

It used to work. And yes, I have the current version.

**Comment by aminomancer** [comment]
Ok, next time include the script name in the title or the description. I have made hundreds of these for random people and never given them a second thought, so you'll have to forgive my memory 😂

**Comment by aminomancer** [comment]
Should be fixed in c324b489ac9cc9d5795d668d6986838cd916caec, try version 1.1.0

**Comment by siffegh** [comment]
Works, thanks a lot.

**Comment by aminomancer** [comment]
Is the new version working for you?
