### ISSUE TITLE
[BUG] Some scripts broke on nightly

### ISSUE THREAD

**Issue by SoSeDiK** [aminomancer/uc.css.js#94]
**Link to the file containing the bug**
https://github.com/aminomancer/uc.css.js/blob/master/JS/verticalTabsPane.uc.js
https://github.com/aminomancer/uc.css.js/blob/master/JS/contextMenuMods.uc.js
https://github.com/aminomancer/uc.css.js/blob/master/JS/openBookmarksHistoryEtcInNewTabs.uc.js

**Describe the bug**
> verticalTabsPane

I can no longer see the vertical tabs pane, can't toggle it with shortcut or button. The button is still shown, but has no icon.

> contextMenuMods

The script was updated recently, but even on `1.0.4` clicking search engine just closes the context menu.

> openBookmarksHistoryEtcInNewTabs

Clicking on bookmarks/history does nothing.

**To Reproduce**
Enable aforementioned modules & test their functionality.

**Expected behavior**
Vertical tabs, search via context menu and opening bookmarks/history are working.

**Screenshots**
The missing vertical tabs icon:

![image](https://github.com/aminomancer/uc.css.js/assets/19875118/d58f85ae-2126-4595-b40e-7a45b0de1837)

**Desktop (please complete the following information):**
 - OS: NixOS unstable with Hyprland git
 - Firefox update channel: Nightly
 - Version: 128.0a1 (2024-05-14) (64-bit)
 - Build ID: 20240514215634

**Comment by aminomancer** [comment]
Thanks for filing, should be fixed now.
