### ISSUE TITLE
[BUG] Context menu search fails to load

### ISSUE THREAD

**Issue by morags** [aminomancer/uc.css.js#99]
**Link to the file containing the bug**
https://github.com/aminomancer/uc.css.js/blob/master/JS/contextMenuMods.uc.js

**Describe the bug**
Context menu search fails to load during browser startup with the following error:

```
Error: @ contextMenuMods.uc.js:84
    tryLoadScriptIntoWindow chrome://userchromejs/content/boot.sys.mjs:193
Caused by: TypeError: this.originalCallback is null
    _searchMenuitem chrome://userscripts/content/contextMenuMods.uc.js:84
    ContextMenuMods chrome://userscripts/content/contextMenuMods.uc.js:44
    <anonymous> chrome://userscripts/content/contextMenuMods.uc.js:291
    injectClassicScriptIntoGlobal chrome://userchromejs/content/boot.sys.mjs:217
    tryLoadScriptIntoWindow chrome://userchromejs/content/boot.sys.mjs:190
    onDOMContent chrome://userchromejs/content/boot.sys.mjs:484
    handleEvent chrome://userchromejs/content/boot.sys.mjs:577
boot.sys.mjs:193:15
    tryLoadScriptIntoWindow chrome://userchromejs/content/boot.sys.mjs:193
```

**To Reproduce**
1. Install fx-autoconfig.
2. Install uc.css.js/contextMenuMods.
3. Run Firefox.
4. Mark some text and right click; the browser displays the default "search with" option.

**Expected behavior**
The default "search with" option has been replaced with a nested menu with a selection of search engines.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox update channel: release
 - Version: 129.0.2
 - Build ID: 20240819150008

**Additional context**
* fx-autoconfig v0.10.1
* uc.css.js/contextMenuMod v1.0.5
* All other mods are loading normally

**Comment by aminomancer** [comment]
Sorry, I haven't had much time to push my changes lately. Try 1.0.6 but feel free to reopen if there are still problems.
